### ISSUE TITLE
Add read more inline just after last word

### ISSUE THREAD

**Issue by laurentgarin** [georapbox/ReadMore.js#3]
Hi,

Thanks for this great and very usefull plugin, this will be breat if it will be possible to add the read more link just after the last word, like this : 

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, voluptatem obcaecati at praesentium sunt voluptatum dolorum. Consequatur, fugiat optio itaque nihil quibusdam repellendus mollitia assumenda placeat debitis reiciendis vel perspiciatis! Lorem ipsum dolor sit amet, consectetur adipisicing elit... **READ MORE...**

Thanks.

**Comment by georapbox** [comment]
Fixed by https://github.com/georapbox/ReadMore.js/pull/7
